// India-first food catalogue — the long tail that IFCT 2017 doesn't cover
// (regional biryanis, street food, restaurant dishes, packaged brands).
//
// Unlike `INDIAN_FOODS`, these values are NOT measured. They are generated by
// `scripts/generate-indian-foods-estimate.ts` from per-category macro baselines
// plus keyword adjustments, so treat them as ballpark figures — they carry the
// `curated` source so the UI can badge them "Estimated" and every ranking path
// prefers a measured row over one of these. Regenerate the JSON via that script
// rather than editing `data/indian-foods.json` by hand.

import rawCuratedFoods from '../data/indian-foods.json'
import { INDIAN_FOODS, type FoodSeed } from './indian-foods-data'

const normalizeName = (name: string): string => name.toLowerCase().replace(/\s+/g, ' ').trim()

const ifctNames = new Set(INDIAN_FOODS.map((f) => normalizeName(f.name)))

/**
 * Curated rows, minus any whose name duplicates a measured IFCT entry.
 *
 * ~60 names overlap (Veg Biryani, Naan, Aloo Paratha …). Both rows would
 * otherwise sit in the shared `foods` table and search would pick between them
 * on ordering alone — so a Chicken Biryani estimated at 8 g protein could
 * shadow the measured IFCT row at 10.2. Dropping them at the source is simpler
 * than defending the ordering forever.
 */
export const CURATED_FOODS: FoodSeed[] = (rawCuratedFoods as FoodSeed[]).filter(
  (f) => !ifctNames.has(normalizeName(f.name))
)
