// India-first food catalogue — the long tail that IFCT 2017 doesn't cover
// (regional biryanis, street food, restaurant dishes, packaged brands).
//
// Unlike `INDIAN_FOODS`, these values are NOT measured. They are generated by
// `scripts/generate-indian-foods-estimate.ts` from per-category macro baselines
// plus keyword adjustments, so treat them as ballpark figures. They carry the
// `curated` source, which every ranking and clustering path treats as less
// trusted than a measured row (`SOURCE_RANK` in `lib/foodMatch.ts`). Regenerate
// the JSON via that script rather than editing `data/indian-foods.json` by hand.

import rawCuratedFoods from '../data/indian-foods.json'
import { INDIAN_FOODS, type FoodSeed } from './indian-foods-data'
import { foodClusterKey } from './foodClusterKey'

const ifctClusterKeys = new Set(INDIAN_FOODS.map((f) => foodClusterKey(f)))

/**
 * Curated rows, minus any that cluster with a measured IFCT entry — same
 * identity `foodClusterKey` uses at search time (`lib/mergeSearchResults.ts`),
 * so a row dropped here is exactly a row that would have lost the collapse
 * anyway. Filtering at the source means the seed data itself never carries
 * the duplicate, rather than relying on every consumer to collapse it.
 *
 * This catches more than an exact-name check would: a curated "Boiled Egg"
 * and a measured "Boiled Egg (Anda)" are different strings but the same food,
 * and previously both shipped — the estimate at 108 kcal/100g sitting beside
 * the measured 173, both visible in search with no way to tell which to
 * trust. `foodClusterKey` strips the regional gloss before comparing, so this
 * one now catches it. ~137 curated names collide with a measured row this
 * way (regional biryanis, street food, packaged brands do not, and remain).
 */
export const CURATED_FOODS: FoodSeed[] = (rawCuratedFoods as FoodSeed[]).filter(
  (f) => !ifctClusterKeys.has(foodClusterKey(f))
)
