// India-first food catalogue — the long tail that IFCT 2017 doesn't cover
// (regional biryanis, street food, restaurant dishes, packaged brands).
//
// Unlike `INDIAN_FOODS`, these values are NOT measured. They are generated by
// `scripts/generate-indian-foods-estimate.ts` from per-category macro baselines
// plus keyword adjustments, so treat them as ballpark figures — they carry the
// `curated` source so the UI can badge them "Estimated" and every ranking path
// prefers a measured row over one of these. Regenerate the JSON via that script
// rather than editing `data/indian-foods.json` by hand.

import rawCuratedFoods from '../data/indian-foods.json'
import { INDIAN_FOODS, type FoodSeed } from './indian-foods-data'

const normalizeName = (name: string): string => name.toLowerCase().replace(/\s+/g, ' ').trim()

const ifctNames = new Set(INDIAN_FOODS.map((f) => normalizeName(f.name)))

// IFCT often glosses a dish with a vernacular or descriptive parenthetical —
// "Boiled Egg (Anda)", "Apple (Seb)", "Butter Chicken (Murgh Makhani)". The
// curated catalogue names the same dish without the gloss ("Boiled Egg",
// "Apple"), so an exact-name check misses the collision and both rows ship:
// the measured IFCT row and an estimate of the identical food right next to it
// in search. Treat the text before a trailing "( … )" as the same name so the
// estimate is dropped and the measured row stands alone. Only the IFCT side is
// stripped — a curated "Omelette (Plain)" vs "Omelette (Masala)" are genuinely
// different dishes and must both survive.
const ifctBaseNames = new Set(
  INDIAN_FOODS.map((f) => normalizeName(f.name).match(/^(.+?) \(.*\)$/)?.[1]).filter(
    (n): n is string => Boolean(n)
  )
)

const duplicatesIfct = (name: string): boolean => {
  const n = normalizeName(name)
  return ifctNames.has(n) || ifctBaseNames.has(n)
}

/**
 * Curated rows, minus any whose name duplicates a measured IFCT entry.
 *
 * ~120 names overlap once the vernacular gloss is accounted for (Veg Biryani,
 * Naan, Aloo Paratha, Boiled Egg, Apple …). Both rows would otherwise sit in
 * the shared `foods` table and search would pick between them on ordering
 * alone — so a Chicken Biryani estimated at 8 g protein could shadow the
 * measured IFCT row at 10.2, or an estimated Boiled Egg read ~40% under the
 * measured one. Dropping them at the source is simpler than defending the
 * ordering forever.
 */
export const CURATED_FOODS: FoodSeed[] = (rawCuratedFoods as FoodSeed[]).filter(
  (f) => !duplicatesIfct(f.name)
)
